### ISSUE TITLE
virtualenv and/or OSX unable to load module

### ISSUE THREAD

**Issue by gmerrall** [metachris/logzero#17] opened 2017-07-07 06:15 UTC
* logzero version: 1.2.0
* Python version: 2.7.10
* Operating System: Mac Sierra 10.12.5

$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.5 (16F73)
      Kernel Version: Darwin 16.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: REMOVED
      User Name: REMOVED
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3 days 7:22

### Description

Using virtualenvwrapper I can't seem to load logzero. Unsure of direct issue

```
$ mkvirtualenv foo
New python executable in /Users/REMOVED/.virtualenvs/foo/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/REMOVED/.virtualenvs/foo/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/REMOVED/.virtualenvs/foo/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/REMOVED/.virtualenvs/foo/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/REMOVED/.virtualenvs/foo/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/REMOVED/.virtualenvs/foo/bin/get_env_details


(foo)$ pip install logzero
Collecting logzero
  Using cached logzero-1.2.0-py2.py3-none-any.whl
Installing collected packages: logzero
Successfully installed logzero-1.2.0

$ ls -ld /Users/REMOVED/.virtualenvs/foo/lib/python2.7/site-packages/logzero
drwxr-xr-x  4 REMOVED  group  136 Jul  7 15:20 /Users/gmerrall/.virtualenvs/foo/lib/python2.7/site-packages/logzero

(foo)$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import sys
>>> import pprint
>>> pprint.pprint(sys.path)
['',
 '/Users/REMOVED/.virtualenvs/foo/lib/python27.zip',
 '/Users/REMOVED/.virtualenvs/foo/lib/python2.7',
 '/Users/REMOVED/.virtualenvs/foo/lib/python2.7/plat-darwin',
 '/Users/REMOVED/.virtualenvs/foo/lib/python2.7/plat-mac',
 '/Users/REMOVED/.virtualenvs/foo/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/REMOVED/.virtualenvs/foo/lib/python2.7/lib-tk',
 '/Users/REMOVED/.virtualenvs/foo/lib/python2.7/lib-old',
 '/Users/REMOVED/.virtualenvs/foo/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/REMOVED/.virtualenvs/foo/lib/python2.7/site-packages']

>>> from logzero import logger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "logzero.py", line 1, in <module>
    from logzero import logger
ImportError: cannot import name logger
```

**Comment by metachris** [comment] 2017-07-07 17:00
Thanks, I'll look into it tonight!

**Comment by metachris** [comment] 2017-07-07 20:24
Hi,

Thanks for the report with the extensive information! That really helps a log.

I can't reproduce this error with the current version of virtualenvwrapper, and logzero v1.2.0 like you.

Can you please tell me your version of virtualenvwrapper? For me it's 4.7.2:

    $ pip list | grep virtualenvwrapper
    virtualenvwrapper (4.7.2)

**Comment by gmerrall** [comment] 2017-07-08 00:14
It's starting to look like a local machine problem. On my home machine
there's no issues with virtualenvwrapper and logzero.

I'll continue to investigate on the machine having the problem.

**Comment by metachris** [comment] 2017-07-08 08:38
Okay, thanks. I'll close this issue now, please open a new one once we can reliably reproduce this behavior.

**Closed by metachris** 2017-07-08 08:38 UTC
